---
deployment:
          tasks:
                      - export DEPLOYPATH=/home/kgzrwvux/public_html/
                      - /bin/cp * $DEPLOYPATH
                      - /bin/cp -R images $DEPLOYPATH
