---
deployment:
          tasks:
                      - export DEPLOYPATH=/home/kgzrwvux/rfrankweb.com/
                      - /bin/cp -R * $DEPLOYPATH
                      - /bin/cp * $DEPLOYPATH
