---
deployment:
          tasks:
                      - export DEPLOYPATH=/home/kgzrwvux/public_html/rfrankweb
                      - /bin/cp -R * $DEPLOYPATH
                      - /bin/cp * $DEPLOYPATH
